Moved fs-extra to dependencies
Sails uses fs-extra. On production, my app now doesn't start because it's missing fs-extra. Example: `node_modules/sails/lib/router/res.js`

Output on my server:

```
islive@node01 ~/apps/fortress (master)
$ node app.js
{ [Error: Cannot find module 'fs-extra'] code: 'MODULE_NOT_FOUND' }
To run an app using `node app.js`, you usually need to have a version of `sails` installed in the same directory as your app.
To do that, run `npm install sails`

Alternatively, if you have sails installed globally (i.e. you did `npm install -g sails`), you can use `sails lift`.
When you run `sails lift`, your app will still use a local `./node_modules/sails` dependency if it exists,
but if it doesn't, the app will run with the global sails instead!
```

After installing fs-extra in node_modules everything worked just fine.