Allow routes named with `Controller` in it
Custom routes like:
'/somecontroller': 'SomeControllerController.action'
Produce the following error message:
error: Ignored attempt to bind route (/somecontroller) to unknown controller :: some.

Because the `controllerId` is normalized two times using
`sailsUtil.normalizeControllerId()`. Once before the call to
`bindController()` and a second time inside the function.

So when trying to bind a custom route I chose to use the original
controller name instead of the previously normalized one.